######################################################################
# Automatically generated by qmake (2.01a) ? 6? 7 22:29:15 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += soeditor.h
SOURCES += main.cpp MainWindow.cpp SOEKeyBind.cpp sotextedit.cpp Widget.cpp
