######################################################################
<<<<<<< HEAD
# Automatically generated by qmake (2.01a) ? 6? 3 15:14:54 2011
=======
# Automatically generated by qmake (2.01a) ? 6? 6 21:29:21 2011
>>>>>>> 7a0a0b6f61ad52e00304bded4cb3d02e1b48396a
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += soeditor.h
SOURCES += main.cpp MainWindow.cpp SOEKeyBind.cpp sotextedit.cpp Widget.cpp
